services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: cme
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: whasC123
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - minha-rede
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 setup.wsgi:application"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment: 
      - DB_HOST=db
      - DB_NAME=cme
      - DB_USER=admin
      - DB_PASSWORD=whasC123
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - minha-rede
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://backend:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    networks:
      - minha-rede
volumes:
  postgres_data:
networks:
  minha-rede:
    driver: bridge