# Generated by Django 5.2 on 2025-04-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('funcao', models.CharField(choices=[('Administrador', 'Administrador'), ('Técnico', 'Técnico'), ('Enfermagem', 'Enfermagem')], default='Técnico', max_length=15)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('senha_hash', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'usuarios_usuario',
            },
        ),
    ]
