# Generated by Django 5.2 on 2025-04-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='funcao',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Técnico', 'Tecnico'), ('Enfermagem', 'Enfermagem')], default='Técnico', max_length=15),
        ),
    ]
