# Generated by Django 5.2 on 2025-04-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=70, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=70)),
                ('data', models.DateField(max_length=70)),
            ],
        ),
    ]
